### ISSUE TITLE
noflip no longer works for the class names

### ISSUE THREAD

**Issue by ccpu** [styled-components/stylis-plugin-rtl#29]
Apparently `noflip` no longer works for the class names, it used to work on last version.

```css
  /* @noflip */
  .foo {
    left: 20px;
  }
```

[here is an example](https://codesandbox.io/s/emotion-rtl-yguj2?file=/index.js:274-442)
